### ISSUE TITLE
Its my understanding problem.

### ISSUE THREAD

**Issue by kaushik1105** [adamenagy/iLogicFormExtractor#2]
Hi @adamenagy,
Thanks for your sharing your great knowledge to the world.

Regarding this logicformExtractor, I am getting following error. [ I have another request, if I create forms (Multiple), How can I share with clients using Forge. If I am using Configurator, it is only showing one form]

Running 'Post activity'
Creating activity 'iLogicFormExtractor'
System.Net.Http.HttpRequestException: The server returned the non-success status code 400 (Bad Request).
More error details:
{"commandLine":["Invalid switch [$(appbundles[iLogicFormExtractor].path)]. Variables that expand to paths must be quoted.Invalid switch [$(args[InputDoc].path)]. Variables that expand to paths must be quoted. (Parameter 'commandLine')"]}.
   at Autodesk.Forge.Core.HttpResponseMessageExtensions.EnsureSuccessStatusCodeAsync(HttpResponseMessage msg)
   at Autodesk.Forge.DesignAutomation.Http.ActivitiesApi.CreateActivityAsync(Activity item, String scopes, IDictionary`2 headers, Boolean throwOnError)
   at Autodesk.Forge.DesignAutomation.DesignAutomationClient.CreateActivityAsync(Activity item)
   at Autodesk.Forge.DesignAutomation.DesignAutomationClient.CreateActivityAsync(Activity activity, String label)
   at Interaction.Publisher.PublishActivityAsync() in G:\Autodesk Forge\Design Automation\iLogicFormExtractor-working but\iLogicFormExtractor\Interaction\Publisher.cs:line 150
   at Interaction.Program.RunCommand(Publisher publisher, String commandIndex) in G:\Autodesk Forge\Design Automation\iLogicFormExtractor-working but\iLogicFormExtractor\Interaction\Program.cs:line 85
   at Interaction.Program.RunLoop(Publisher publisher) in G:\Autodesk Forge\Design Automation\iLogicFormExtractor-working but\iLogicFormExtractor\Interaction\Program.cs:line 73
   at Interaction.Program.Main(String[] args) in G:\Autodesk Forge\Design Automation\iLogicFormExtractor-working but\iLogicFormExtractor\Interaction\Program.cs:line 42

Press any key to close console...

G:\Autodesk Forge\Design Automation\iLogicFormExtractor-working but\iLogicFormExtractor\Interaction\bin\x64\Debug\netcoreapp3.1\Interaction.exe (process 18520) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

**Comment by adamenagy** [comment]
This is the problem with the commandLine you are trying to use: https://forge.autodesk.com/blog/design-automation-command-line

**Comment by kaushik1105** [comment]
Hi @adamenagy 

Thanks a lot for your reply. I am grateful that I am able to get a chance to interact with you.
I tried to understand the commandline comments. I would like to know what should I put in url.

return new Dictionary<string, IArgument>
                    {
                        {
                            Constants.Parameters.InputDoc,
                            new XrefTreeArgument
                            {
                                Url = ""
                            }
                        },
                        {
                            Constants.Parameters.OutputJson,
                            new XrefTreeArgument
                            {
                                Verb = Verb.Put,
                                Url = ""
                            }
                        }
                    };
Thank you again.

**Comment by kaushik1105** [comment]
Hi @adamenagy 

I found the reply of my query  in below blog
https://forge.autodesk.com/blog/design-automation-inventor-vs-template-run-workitem

Thanks a lot. You are genius.

**Comment by adamenagy** [comment]
Glad I could help 😀
